[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"
authors = ["Xiaobin Li <l_xb@foxmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
oneshot = "0.1"
rand = "0.8"
